// <auto-generated />
namespace CustomerManagement.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class SomethingChanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SomethingChanged));
        
        string IMigrationMetadata.Id
        {
            get { return "201410200134182_SomethingChanged"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
